[env]
TERM = "xterm-256color"

[font]
size = 11

[font.bold]
family = "Noto Fonts"
style = "Bold"

[font.bold_italic]
family = "Noto Fonts"
style = "Bold Italic"

[font.italic]
family = "Noto Fonts"
style = "Italic"

[font.normal]
family = "Noto Fonts"
style = "Regular"

[font.offset]
x = 0
y = 1

[scrolling]
history = 5000

[shell]
args = [""]
program = "sh"

[window]
title = "Alacritty"

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.padding]
x = 6
y = 6
